import os
from building import *

Import('SIFLI_SDK')

dfu_pan_dir = os.path.join(SIFLI_SDK, 'middleware/dfu_pan')
src = [
    'hsp_bt_pan_ota.c',
    'hsp_dfu_pan_flash.c',
]

group = DefineGroup('hsp_ota_client', src,
                    depend=['HSP_USING_OTA'],
                    CPPPATH=[dfu_pan_dir])

Return('group')
