// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    rt_kprintf("[lvgl][ui] ui_init begin dispp=%p\r\n", dispp);
#if LV_USE_THEME_DEFAULT
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
#elif LV_USE_THEME_BASIC
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
#else
    (void)dispp;
#endif
    ui_Screen2_screen_init();
    rt_kprintf("[lvgl][ui] Screen2=%p\r\n", ui_Screen2);
    ui_ScreenHome_screen_init();
    rt_kprintf("[lvgl][ui] ScreenHome=%p\r\n", ui_ScreenHome);
    ui_Screen3_screen_init();
    rt_kprintf("[lvgl][ui] Screen3=%p keyboard=%p textarea=%p\r\n", ui_Screen3, ui_Keyboard1, ui_TextArea1);
    ui____initial_actions0 = lv_obj_create(NULL);
    rt_kprintf("[lvgl][ui] initial_actions=%p\r\n", ui____initial_actions0);
    lv_disp_load_scr(ui_Screen2);
    rt_kprintf("[lvgl][ui] loaded screen=%p active=%p\r\n", ui_Screen2, lv_scr_act());
}

void ui_destroy(void)
{
    ui_Screen2_screen_destroy();
    ui_ScreenHome_screen_destroy();
    ui_Screen3_screen_destroy();
}
