// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Spinbox1;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Slider1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

