import os
from building import *

SIFLI_SDK = os.getenv('SIFLI_SDK')
objs = []

objs.extend(SConscript(
    os.path.join(SIFLI_SDK, 'example/dfu_pan/src/SConscript'),
    variant_dir='dfu_pan',
    duplicate=0,
))
objs.extend(SConscript(
    os.path.join(SIFLI_SDK, 'example/dfu_pan/assets/SConscript'),
    variant_dir='ota_assets',
    duplicate=0,
))
objs.extend(SConscript(
    os.path.join(SIFLI_SDK, 'SConscript'),
    variant_dir='sifli_sdk',
    duplicate=0,
))

Return('objs')
