import os
from building import *

cwd = GetCurrentDir()
module_dirs = [
    'app',
    'drivers',
    'services',
    'bluetooth',
    'ui/details',
    'ui/music',
    'ui/generated',
    'ui/generated/components',
    'ui/generated/screens',
]

src = []
for module_dir in module_dirs:
    src += Glob(os.path.join(module_dir, '*.c'))

include_dirs = [cwd]
include_dirs += [os.path.join(cwd, module_dir) for module_dir in module_dirs]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = include_dirs)

Return('group')
