from building import *
import rtconfig
import os

src = []
inc = []
cwd = GetCurrentDir() # get current dir path

src = Glob('*.c')
src += Glob('ui/*.c') + Glob('ui/screens/*.c') + Glob('ui/components/*.c')

inc = inc + [cwd, cwd + '/ui']

group = DefineGroup('LVGL_EXAMPLE', src, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = inc)
Return('group')
